### ISSUE TITLE
[LCO_tool_V2.3.0] Impossible to generate license (Validas)

### ISSUE THREAD

**Issue by JoanMouba** [arsysop/cordon-support#5]
Hello, 
I cannot generate a TCA license. 
It looks like the Grants are duplicated. 

The data and meta data were created in the previous LCO 5.0 RC2

Regards, 
Joan

![LCO_Validas_issue](https://user-images.githubusercontent.com/43171207/182205634-e966dd0a-6b2d-4ae1-9031-9c46fcfe573b.PNG)

**Comment by JoanMouba** [comment]
![LCO_Validas_issue2](https://user-images.githubusercontent.com/43171207/182206468-16befc84-2fbb-46a2-b266-9d897c0d6b96.PNG)

**Comment by eparovyshnaya** [comment]
Two issues here: 
 - usability: raw emf validation output must be delivered to end user  
     - by proper explanation
     - in suitable ui
- data transfer: in several cases User's preffered condition appears to be harmed and does not make it to a grant. In LCO ui you see a user having `hardware` value set to `preferred evaluation type`, but it does not appear in appropriate xmi data file and thus does not go to a license grant.

**Comment by eparovyshnaya** [comment]
Fixed in 2.11.1 Peacock
