### ISSUE TITLE
[Validas] LCO 2.3.1 - No more possible to edit the grants

### ISSUE THREAD

**Issue by JoanMouba** [arsysop/cordon-support#9]
Hello, 
When I select a License Pack in the new LCO V2.3.1, in the issue License dialog. 
It’s no more possible to edit the Grants. 
In the previous version, it was possible to remove some. 
Is it normal or a missing feature ? 
Regards, 
Joan - Validas AG
![GrantsNoEditable_LCO231](https://user-images.githubusercontent.com/43171207/188443397-04cf2139-862b-4cf7-86aa-a959d04abf2d.PNG)

**Comment by eparovyshnaya** [comment]
done to common Passage source base with [Passage MR #1174](https://github.com/eclipse-passage/passage/pull/1174)
